Add Deck and Update Deck handle all cards as well
Revature-Overcharge/rev-Overcharge pull request #11
Opened 2021-08-18 20:27 UTC by SeanGRev

2021-08-18 20:56 UTC, JosephLamacchia approved these changes

2021-08-18 21:47 UTC, kileader requested changes
I think update is going to be more difficult then that. It should have adds, deletes, and updates for cards.

2021-08-18 23:39 UTC, kileader commented
I just made a new pull request for an easy edit on this one.

2021-08-18 23:44 UTC, kileader approved these changes

2021-08-19 14:39 UTC, SeanGRev commented
Adds some annotations to the main ApplicationClass

2021-08-19 14:57 UTC, kileader approved these changes

2021-08-19 15:01 UTC, ChristopherNowalk approved these changes

2021-08-19 15:42 UTC, merged