Newdwaynebranch
Revature-Overcharge/rev-Overcharge pull request #30
Opened 2021-08-20 19:19 UTC by dwayne-revature

- (Dwayne)  Ratings Back End Service and Controller Implementations Added
- Need to Test

2021-08-20 20:05 UTC, kileader requested changes
Try modeling the controller off of CardController and DeckController. "/search" isn't necessary and should be implied by the http method being a GET. Your postman body should be really simple for a POST request. Something with only the user Id, deck Id, and stars should be sufficient, as the date should be added in the service, and the objects can be gotten through the database. You should be able to use the methods already in the repos that you deleted.

2021-08-21 12:44 UTC, jhupprevature commented
Due to refactoring for front-end naming conventions, please confirm a new **merge from main** before approval.

2021-08-21 20:20 UTC, stukruze approved these changes

2021-08-22 01:29 UTC, closed without merging

2021-08-22 01:29 UTC, dwayne-revature commented
Re-did the changes on another branch